import { library } from '@fortawesome/fontawesome-svg-core'

import {
    faArrowRightToBracket,
    faBars,
    faBook,
    faCalendarDay,
    faClock,
    faDownload,
    faEllipsisStrokeVertical,
    faEnvelope,
    faFileInvoice,
    faFireFlameCurved,
    faFolderUser,
    faGauge,
    faKey,
    faReceipt,
    faShare,
    faStar,
    faUserPlus,
    faUsers,
} from '@fortawesome/pro-regular-svg-icons'

library.add(
    faArrowRightToBracket,
    faBars,
    faBook,
    faCalendarDay,
    faClock,
    faDownload,
    faEllipsisStrokeVertical,
    faEnvelope,
    faFileInvoice,
    faFireFlameCurved,
    faFolderUser,
    faGauge,
    faKey,
    faReceipt,
    faShare,
    faStar,
    faUserPlus,
    faUsers,
)
