/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthenticatedLayout: typeof import('./../../views/Layouts/AuthenticatedLayout.vue')['default']
    GuestLayout: typeof import('./../../views/Layouts/GuestLayout.vue')['default']
    Icon: typeof import('./../../views/Components/Icon.vue')['default']
  }
}
